/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface AppTodo {
    }
    interface FormTodo {
    }
    interface ListTodo {
        "list": string[];
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTodoElement extends Components.AppTodo, HTMLStencilElement {
    }
    var HTMLAppTodoElement: {
        prototype: HTMLAppTodoElement;
        new (): HTMLAppTodoElement;
    };
    interface HTMLFormTodoElement extends Components.FormTodo, HTMLStencilElement {
    }
    var HTMLFormTodoElement: {
        prototype: HTMLFormTodoElement;
        new (): HTMLFormTodoElement;
    };
    interface HTMLListTodoElement extends Components.ListTodo, HTMLStencilElement {
    }
    var HTMLListTodoElement: {
        prototype: HTMLListTodoElement;
        new (): HTMLListTodoElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "app-todo": HTMLAppTodoElement;
        "form-todo": HTMLFormTodoElement;
        "list-todo": HTMLListTodoElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface AppTodo {
    }
    interface FormTodo {
        "onAddTask"?: (event: CustomEvent<any>) => void;
    }
    interface ListTodo {
        "list"?: string[];
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "app-todo": AppTodo;
        "form-todo": FormTodo;
        "list-todo": ListTodo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-todo": LocalJSX.AppTodo & JSXBase.HTMLAttributes<HTMLAppTodoElement>;
            "form-todo": LocalJSX.FormTodo & JSXBase.HTMLAttributes<HTMLFormTodoElement>;
            "list-todo": LocalJSX.ListTodo & JSXBase.HTMLAttributes<HTMLListTodoElement>;
        }
    }
}
